# Generated by Django 3.2 on 2021-04-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areamastermodel',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=100, verbose_name='Area Type')),
            ],
        ),
        migrations.CreateModel(
            name='Gamesmastermodel',
            fields=[
                ('Gameid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Game', models.CharField(max_length=100, verbose_name='Game Name')),
                ('Description', models.TextField(max_length=500, verbose_name='Description')),
                ('Maxparticipants', models.IntegerField(verbose_name='Max Participants')),
                ('Minparticipants', models.IntegerField(verbose_name='Min Participants')),
            ],
        ),
        migrations.CreateModel(
            name='Locationtypemodel',
            fields=[
                ('Locationid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Locationtype', models.CharField(max_length=100, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Menucategorymodel',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=100, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Menumastermodel',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Menuname', models.CharField(max_length=100, verbose_name='Menu')),
                ('Area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.areamastermodel')),
                ('Menucategory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.menucategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Menupreferencemastermodel',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Menupreference', models.CharField(max_length=100, verbose_name='Menu Preference')),
            ],
        ),
        migrations.CreateModel(
            name='Partymastermodel',
            fields=[
                ('Partyid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Partyname', models.CharField(max_length=100, verbose_name='Party Name')),
                ('Date', models.DateField(verbose_name='Date of Party')),
                ('Time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Time')),
                ('Attendeesno', models.IntegerField(verbose_name='Attendees No')),
                ('PartyInout', models.CharField(max_length=100, verbose_name='Party In(food)')),
                ('Locationtype', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.locationtypemodel')),
                ('Menupreference', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.menupreferencemastermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Venumastermodel',
            fields=[
                ('Venuid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Venu', models.CharField(max_length=100, verbose_name='Venu')),
                ('Locationtype', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.locationtypemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Partymenubridgemodel',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.menumastermodel')),
                ('Party', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.partymastermodel')),
            ],
        ),
        migrations.AddField(
            model_name='partymastermodel',
            name='Venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.venumastermodel'),
        ),
        migrations.CreateModel(
            name='Partygamebridgemodel',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.gamesmastermodel')),
                ('Party', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.partymastermodel')),
            ],
        ),
        migrations.AddField(
            model_name='menumastermodel',
            name='Menupreference',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.menupreferencemastermodel'),
        ),
        migrations.CreateModel(
            name='Inviteesmastermodel',
            fields=[
                ('Invittesid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Inviteename', models.CharField(max_length=100, verbose_name='Name')),
                ('Phonenumber', models.CharField(max_length=100, verbose_name='Phone No')),
                ('Whatsapp', models.CharField(max_length=100, verbose_name='Whatsapp')),
                ('Address', models.CharField(max_length=250, verbose_name='Address')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Gender', models.CharField(max_length=15, verbose_name='Gender')),
                ('Adultorkid', models.CharField(max_length=100, verbose_name='Adult/Kid')),
                ('Menupreference', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.menupreferencemastermodel')),
            ],
        ),
        migrations.AddField(
            model_name='gamesmastermodel',
            name='Locationtype',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.locationtypemodel'),
        ),
        migrations.CreateModel(
            name='Bringaplatemodel',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(verbose_name='Quantity')),
                ('Invitees', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.inviteesmastermodel')),
                ('Menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.menumastermodel')),
                ('Party', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.partymastermodel')),
            ],
        ),
    ]
