# Generated by Django 3.2 on 2021-04-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyInviteesbridgemodel',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Invitees', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.inviteesmastermodel')),
                ('Party', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='partyapp.partymastermodel')),
            ],
        ),
    ]
