# Generated by Django 3.2 on 2021-04-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0002_partyinviteesbridgemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymastermodel',
            name='Game',
            field=models.ManyToManyField(related_name='Partymastermodel', through='partyapp.Partygamebridgemodel', to='partyapp.Gamesmastermodel'),
        ),
        migrations.AlterField(
            model_name='partygamebridgemodel',
            name='Game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_game_bridge_model', to='partyapp.gamesmastermodel'),
        ),
        migrations.AlterField(
            model_name='partygamebridgemodel',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_game_bridge_model', to='partyapp.partymastermodel'),
        ),
    ]
