# Generated by Django 3.2 on 2021-06-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0007_alter_partymastermodel_invitees'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmastermodel',
            name='Gametype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Game Type'),
        ),
        migrations.AlterField(
            model_name='partymastermodel',
            name='Invitees',
            field=models.ManyToManyField(related_name='Partymastermodel', through='partyapp.Partyinviteesbridgemodel', to='partyapp.Inviteesmastermodel'),
        ),
    ]
